apiVersion: apps/v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: pv-example
spec:
 storageClassName: manual
 selector:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 2Gi
